### ISSUE TITLE
How to get the depth value you predicted

### ISSUE THREAD

**Issue by lasxz** [gdlg/panoramic-depth-estimation#3]
The output of your program has only one image and one .npy file. How to get the predicted depth value of the  image?

**Comment by gdlg** [comment]
The .npy contains an array with the depth value for each pixel. You can load the file using the np.load function of numpy. The depth values are in meters.

**Comment by lasxz** [comment]
Thank you very much.

**Comment by lasxz** [comment]
How can point clouds (x, y, z) be recovered from depth values?

**Comment by gdlg** [comment]
Assuming that your image is a 360° equirectangular panorama, the (u,v) coordinates in your image are just the latitude and longitude of each point. Have a look at our paper for the details of the math on equirectangular projections.
