### ISSUE TITLE
Indoor datasets

### ISSUE THREAD

**Issue by efyphil** [gdlg/panoramic-depth-estimation#8]
Thanks for your work! I tried to use your wights for predict indoor scenes, but get very bad result. Did you try to work with indoor?
<img width="1194" alt="Снимок экрана 2020-10-07 в 16 10 58" src="https://user-images.githubusercontent.com/38631588/95335223-cf9ad400-08b7-11eb-9cb2-73b5b18b089b.png">

**Comment by gdlg** [comment]
Hi @efyphil , I worked on autonomous driving datasets and I haven’t tried indoor scenes. The algorithm was trained on the KITTI dataset. I think that the data that I trained on is too different from indoor imagery for the network to generalise well. You might need to train the algorithm on a dataset that contains indoor scenes.

**Comment by efyphil** [comment]
@gdlg  thanks for fast answer. I'll try to train on different dataset, about bad result it's my fault. I didn't crop the image, after cropping it seems better 
<img width="1303" alt="Снимок экрана 2020-10-08 в 11 57 38" src="https://user-images.githubusercontent.com/38631588/95438777-6bcbe600-095f-11eb-817b-b087a75ec586.png">

**Comment by gdlg** [comment]
@efyphil Thanks for the update. For the images that I was working for, cropping was fine. It’s a limitation of the approach that it doesn’t work with the full vertical field of view.
